#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_3x6_3(KC_F3, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, LT(2,KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_PSLS, KC_RSFT, KC_NO, LT(1,KC_BSPC), LGUI_T(KC_TAB), RCTL_T(KC_ENT), LT(1,KC_SPC), LALT_T(KC_NO)),
	[1] = LAYOUT_split_3x6_3(SGUI(KC_X), LALT(KC_7), LALT(KC_2), LSFT(KC_6), LSA(KC_7), LALT(KC_RBRC), KC_PPLS, KC_7, KC_8, KC_9, LALT(KC_8), LALT(KC_9), LCTL(KC_A), KC_EXLM, LSFT(KC_2), KC_HASH, LALT(KC_4), LSFT(KC_5), KC_PEQL, KC_4, KC_5, KC_6, LSFT(KC_8), LSFT(KC_9), SGUI(KC_4), KC_PLUS, KC_GRV, KC_TILD, LSFT(KC_SLSH), KC_SLSH, KC_PIPE, KC_1, KC_2, KC_3, RSA(KC_8), RSA(KC_9), KC_NO, KC_LEFT, KC_RGHT, KC_DOWN, KC_UP, KC_0)
};

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)





